services:
  - type: web
    name: kuspid-artist-management
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    autoDeploy: true

    envVars:
      # --------------------
      # Database (Render Managed PostgreSQL)
      # --------------------
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: kuspid-db
          property: connectionString


      # --------------------
      # JPA / Hibernate
      # --------------------
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update


      # --------------------
      # Security
      # --------------------
      - key: JWT_SECRET
        generateValue: true

      # --------------------
      # Spring / Server
      # --------------------
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: PORT
        value: 8080

      # --------------------
      # Mail (SMTP â€“ set manually in dashboard)
      # --------------------
      - key: MAIL_HOST
        value: smtp.gmail.com

      - key: MAIL_PORT
        value: "587"

      - key: MAIL_USERNAME
        sync: false

      - key: MAIL_PASSWORD
        sync: false

databases:
  - name: kuspid-db
    plan: free
    databaseName: kuspid_artist_management
    user: kuspid_user
